# Generated by Django 5.0.2 on 2024-02-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0002_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myStore.categories'),
        ),
    ]
