# Generated by Django 5.0.2 on 2024-02-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0003_products_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='item_images'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='desciption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
